<%@ Page Title="Merge Projects" Language="C#" MasterPageFile="~/Admin/admin.master" AutoEventWireup="true" CodeFile="ProjectMerge.aspx.cs" Inherits="Admin_ProjectMerge" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cp1" Runat="Server">

    <h3>MERGE TWO PROJECTS</h3>
    <h2 style="color: #FF0000"> Use this page only when students register a project without using the Affiliate-Generated ProjetCode.<br />
        Please make sure you select the correct projects. <br/>This action cannot be UNDONE!!
 </h2>


         <strong>ProjectCode that will be copied to target project and DELETED (Generated by the Affiliate):  </strong> <br/><br/>
   
       <asp:DropDownList ID="ProjectBox1" class="chosen-select"  Width="900px" runat="server" AutoPostBack="True" DataSourceID="AccessDataSource1"
            DataTextField="Project" DataValueField="pid" OnDataBound="ProjectBox1_DataBound"  OnSelectedIndexChanged="ProjectBox1_SelectedIndexChanged">
        </asp:DropDownList>
    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" Display="Dynamic" InitialValue="Select" runat="server" ErrorMessage="*Required" ControlToValidate="ProjectBox1"></asp:RequiredFieldValidator>
   
         <asp:AccessDataSource ID="AccessDataSource1" runat="server" DataFile="~/App_Data/isweeep.mdb"
            SelectCommand="SELECT [ProjectCode] +' - '+[RegionalName] As project,[pid] FROM [Projects] WHERE RegionalID is NOT NULL AND RegionalParticipation=TRUE ORDER BY RegionalID">            
         </asp:AccessDataSource>

      <br/><br/><br/>


        <strong>Target Project:  </strong>  <br/><br/>

       <asp:DropDownList ID="ProjectBox2" class="chosen-select"  Width="900px" runat="server" AutoPostBack="True" DataSourceID="AccessDataSource2"
            DataTextField="Project" DataValueField="pid" OnDataBound="ProjectBox2_DataBound"  OnSelectedIndexChanged="ProjectBox2_SelectedIndexChanged">
        </asp:DropDownList>
     <asp:RequiredFieldValidator ID="RequiredFieldValidator2" Display="Dynamic" InitialValue="Select" runat="server" ErrorMessage="*Required" ControlToValidate="ProjectBox2"></asp:RequiredFieldValidator>
     <br/><br/>
         <asp:AccessDataSource ID="AccessDataSource2" runat="server" DataFile="~/App_Data/isweeep.mdb"
            SelectCommand="SELECT [ProjectCode] +' - '+[Email]+' - '+[Title] As project,[pid] FROM [Projects] WHERE ([Email] is NOT Null)">            
         </asp:AccessDataSource>
    <br/><br/>

    <asp:Label ID="Label1" runat="server" Text="" ForeColor="Red" Font-Bold="True"></asp:Label>
    <br/><br/>
    <asp:Button ID="ButtonMerge" runat="server" Text="Merge Projects" CssClass="btn btn-large" OnClick="ButtonMerge_Click" OnClientClick="return confirm('Are you certain you want to merge these project?')" Visible="False"  />

    <asp:AccessDataSource ID="AccessDataSource3" runat="server" DataFile="~/App_Data/isweeep.mdb"></asp:AccessDataSource>

</asp:Content>

